powerdata <- read.csv("household_power_consumption.txt", header = TRUE, sep = ';')
powerdata$Date<- as.Date(powerdata$Date, "%d/%m/%Y")
test<- subset(powerdata, Date == as.Date('2007-02-01') | Date == as.Date('2007-02-02'))
with(test, hist(as.numeric(Global_active_power)/500, main = "Global Active Power", col = "red",xlab = "Global Active Power(kilowatts)"))
dev.copy(png, "plot1.png", width = 480, height = 480)
dev.off()